import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { db, OperationType, handleFirestoreError } from '../firebase';
import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { motion } from 'framer-motion';
import { Star, Save, AlertCircle, CheckCircle } from 'lucide-react';
import { GoogleGenAI, Type } from "@google/genai";

const Review: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const { user, profile } = useAuth();
  const navigate = useNavigate();
  
  const [interview, setInterview] = useState<any>(null);
  const [candidate, setCandidate] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [ratings, setRatings] = useState({
    technical: 5,
    communication: 5,
    problemSolving: 5,
    confidence: 5,
    professionalism: 5
  });
  const [notes, setNotes] = useState('');

  useEffect(() => {
    if (!id || !user || profile?.role !== 'interviewer') {
      navigate('/dashboard');
      return;
    }

    const fetchDetails = async () => {
      try {
        const interviewSnap = await getDoc(doc(db, 'interviews', id));
        if (interviewSnap.exists()) {
          const data = interviewSnap.data();
          if (data.interviewerId !== user.uid) {
            navigate('/dashboard');
            return;
          }
          setInterview(data);

          const candidateSnap = await getDoc(doc(db, 'users', data.candidateId));
          if (candidateSnap.exists()) {
            setCandidate(candidateSnap.data());
          }
        }
      } catch (err) {
        handleFirestoreError(err, OperationType.GET, `interviews/${id}`);
      } finally {
        setLoading(false);
      }
    };

    fetchDetails();
  }, [id, user, profile, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    setError(null);

    try {
      // 1. Call Gemini API to generate summary and score
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey || apiKey === 'undefined' || apiKey === 'MY_GEMINI_API_KEY' || apiKey === '') {
        throw new Error("GEMINI_API_KEY is missing or invalid. Please add your real Gemini API key to your .env file locally (or to Secrets in AI Studio). You can get one from https://aistudio.google.com/app/apikey");
      }

      const ai = new GoogleGenAI({ apiKey });
      
      const prompt = `
        You are an expert technical recruiter. 
        Review the following interviewer notes and ratings for a candidate named ${candidate?.displayName || 'the candidate'}.
        
        Ratings (out of 10):
        - Technical: ${ratings.technical}
        - Communication: ${ratings.communication}
        - Problem Solving: ${ratings.problemSolving}
        - Confidence: ${ratings.confidence}
        - Professionalism: ${ratings.professionalism}
        
        Interviewer Notes:
        "${notes}"
        
        Provide a professional summary and an overall score.
      `;

      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: prompt,
        config: {
          systemInstruction: "You represent the AI Assessment layer of InterviewPortfolio. Your summary should be objective, data-driven, and professional. Return valid JSON only.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              aiSummary: { type: Type.STRING, description: "A professional 2-3 paragraph summary of the interview performance." },
              aiFeedbackTone: { type: Type.STRING, description: "Phrase describing the tone (e.g., 'Analytical', 'Critical')." },
              aiScore: { type: Type.NUMBER, description: "Single overall score out of 10." }
            },
            required: ["aiSummary", "aiFeedbackTone", "aiScore"]
          }
        }
      });

      const aiResult = JSON.parse(response.text || '{}');

      // 2. Update Firestore document
      await updateDoc(doc(db, 'interviews', id!), {
        status: 'reviewed',
        ratings,
        interviewerComments: notes,
        aiSummary: aiResult.aiSummary || "Summary generated by AI.",
        aiFeedbackTone: aiResult.aiFeedbackTone || "Professional",
        aiScore: parseFloat(aiResult.aiScore?.toString() || '8.0') || 8.0
      });

      navigate('/dashboard');
    } catch (err: any) {
      console.error("Error submitting review:", err);
      setError(err.message || "Failed to submit review. Please try again.");
    } finally {
      setSubmitting(false);
    }
  };

  if (loading) return <div className="min-h-screen flex items-center justify-center">Loading...</div>;
  if (!interview || !candidate) return <div className="min-h-screen flex items-center justify-center">Data not found.</div>;

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white p-8 lg:p-12 rounded-[3rem] shadow-xl border border-gray-100"
      >
        <div className="mb-10 text-center">
          <div className="w-20 h-20 bg-emerald-100 rounded-3xl flex items-center justify-center mx-auto mb-6">
            <Star className="text-emerald-600 w-10 h-10 fill-emerald-600" />
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Review Candidate</h1>
          <p className="text-gray-600">Submit your ratings and notes for {candidate.displayName}</p>
        </div>

        {error && (
          <div className="mb-8 p-4 bg-red-50 border border-red-100 rounded-2xl flex items-start text-red-600">
            <AlertCircle className="w-5 h-5 mr-3 mt-0.5 flex-shrink-0" />
            <p className="text-sm font-medium">{error}</p>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {Object.entries(ratings).map(([key, value]) => (
              <div key={key} className="bg-gray-50 p-6 rounded-2xl">
                <label className="block text-sm font-bold text-gray-700 capitalize mb-4">
                  {key.replace(/([A-Z])/g, ' $1').trim()}
                </label>
                <div className="flex items-center space-x-4">
                  <input 
                    type="range" 
                    min="1" 
                    max="10" 
                    value={value}
                    onChange={(e) => setRatings({...ratings, [key]: parseInt(e.target.value)})}
                    className="w-full accent-indigo-600"
                  />
                  <span className="font-bold text-indigo-600 w-8 text-right">{value}/10</span>
                </div>
              </div>
            ))}
          </div>

          <div>
            <label className="block text-sm font-bold text-gray-700 mb-3">
              Interviewer Notes
            </label>
            <textarea
              required
              rows={6}
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Provide detailed feedback on the candidate's performance, strengths, and areas for improvement..."
              className="w-full p-4 bg-gray-50 border border-gray-200 rounded-2xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-all outline-none resize-none"
            />
          </div>

          <div className="bg-indigo-50 p-6 rounded-2xl flex items-start">
            <CheckCircle className="w-5 h-5 text-indigo-600 mr-3 mt-0.5 flex-shrink-0" />
            <p className="text-sm text-indigo-900 leading-relaxed">
              <strong>AI Processing:</strong> Your notes and ratings will be processed by our AI to generate a comprehensive summary and final score for the candidate's portfolio.
            </p>
          </div>

          <div className="flex justify-end space-x-4 pt-6 border-t border-gray-100">
            <button
              type="button"
              onClick={() => navigate('/dashboard')}
              className="px-8 py-4 bg-gray-50 text-gray-600 rounded-2xl font-bold hover:bg-gray-100 transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={submitting}
              className="px-8 py-4 bg-indigo-600 text-white rounded-2xl font-bold shadow-lg shadow-indigo-100 hover:bg-indigo-700 transition-all flex items-center disabled:opacity-50"
            >
              {submitting ? 'Processing AI Review...' : 'Submit Review'}
            </button>
          </div>
        </form>
      </motion.div>
    </div>
  );
};

export default Review;
